version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/reactive
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 1234
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reactive
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: reactive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
